### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by amandakrohn** [amandakrohn/Javascript#11]
### To do
- [x] Document On-boarding experience, #1 
- [x] Check the current complexity, #8 , and document findings #2 
- [x] Implement manual branch coverage tool, #9, and document #4 
- [x] Improve coverage, #10, and document #5 
- [x] Document refactor plan, #3 
- [x] Assess and document way of working, #6 
- [x] Document over-all experience, #7 

### Grading criteria
**Pass (P)**
1. You provide a coherent account of your onboarding experience.
2. You identify ten functions/methods with high complexity, and document the purpose of them, and why the complexity should be high (or not). You also manually count the complexity of five functions (on paper or as comments).
3. You clearly describe how to refactor five complex functions into smaller functions.
4. You create a working ad-hoc coverage tool that at least measures coverage of normal branches (if, while) for five functions.
5. Each group member writes at least two new tests that improve coverage, as evidenced by the coverage tool. All tests have at least one meaningful assertion (other than “assert(true)” or equivalent).
6. You provide a coherent account of your self-assessment according to the Essence standard.

**Pass with distinction (P+), 3 out of these 5 points**
1. Each group member writes at least four new or enhanced unit tests (twice as many as for P).
2. You use your issue tracker and systematic commit messages to manage your project.
3. You carry out some of Task 3: you refactor at least two of the functions (per group member) with high cyclomatic complexity to reduce it by at least 35 % (for example, by splitting the functions).
4. You get a patch with new tests or a refactoring accepted. Note: the patch must be submitted by the assignment deadline, but it may be accepted later; as long as it is accepted by the end of the course, this point is counted.
5. Something else that is extraordinary, at the discretion of the examiner.

**Presentation**
In the grading session, the group has to
- present some of the complex functions in the grading session,
- show complexity metrics and explain their ramifications, and
- show coverage before and after the new tests (measured by external tools and their own tool).
Furthermore, the coverage measurement implementation and some of the new test cases will be inspected.

**Comment by amandakrohn** [comment]
Since we are finished, I will close this issue.
